// todo-react-frontend/src/components/AddTodo.jsx
import React from "react";
//import {PostTodo} from '../repositories/TodoRepository'

export default class AddTodo extends React.Component {
  constructor(props) {
    super();
    this.state = {
      todo: {
        Name: "",
      },
    };
  }

  render() {
    return (
      <div className="input-group mb-3">
        <input
          type="text"
          className="form-control"
          placeholder="Todo..."
          aria-label="Recipient's username"
          aria-describedby="button-addon2"
          value={this.state.todo.Name}
          onChange={(e) => {
            this.setState({ todo: { Name: e.target.value } });
          }}
        />
        <div className="input-group-append">
          <button className="btn btn-primary" type="button" id="button-addon2">
            Add
          </button>
        </div>
      </div>
    );
  }
}

// todo/src/components/AddTodo.vue
<template>
  <div class="input-group mb-3">
    <input
      type="text"
      class="form-control"
      placeholder="Todo..."
      aria-label="Recipient's username"
      aria-describedby="button-addon2"
      text="lol"
      v-model="todoName"
       @keydown.enter = "postTodo"
    />
    <div class="input-group-append">
      <button class="btn btn-primary" type="button" id="button-addon2" v-on:click="postTodo" >Add</button>
    </div>
  </div>
</template>

<script>
export default {
  name: "AddTodo",
  data: function() {
    return {
      todoName: null,
      processing: false
    };
  },
  methods: {
    postTodo: function() {
      if (this.todoName !== null) {
        this.$api
          .post("/todo/todo", {
            Name: this.todoName
          })
          .then(response => {
            console.log(response);
            this.$emit('postTodo')
          })
          .catch(function(error) {
            console.log(error);
          })
          .finally(() => console.log("OK"));

        this.todoName = null;
       
      }
    }
  }
};
</script>
